### ISSUE TITLE
Is Rider supported?

### ISSUE THREAD

**Issue by JesseTG** [nsubstitute/NSubstitute.Analyzers#116]
Is JetBrains Rider supported, or just Visual Studio?

**Comment by tpodolak** [comment]
Judging by Rider's blog, Roslyn analyzers are supported starting from version 2018.1, so NSubstitute.Analyzers should be working on Rider as well (as there is no code which would require VisualStudio as a dependency). I've briefly tested it against Rider 2019.2 EAP and everything seems to be working fine
![image](https://user-images.githubusercontent.com/7378346/61592385-df56cb80-abd2-11e9-8c38-96f84c56ab49.png)

**Comment by JesseTG** [comment]
Is there a guide to setting it up for Rider?  I'm new to Rider, NSubstitute, this package, and Roslyn analyzers in general.

**Comment by tpodolak** [comment]
All you have to do is to install NSubstitute.Analyzers.CSharp or NSubstitute.Analyzers.VisualBasic package in your project and then follow the steps from the Jetbainrs Rider manual
https://www.jetbrains.com/help/rider/Using_NET_Compiler_Analyzers.html. Once you've done the steps you can test if analyzers work by violating any of the NSubstitute.Analyzers rules

**Comment by JesseTG** [comment]
Thank you, I'll try that and let you know if I have any more problems.

**Comment by tpodolak** [comment]
Closing as there is nothing to do on our side. @JesseTG feel free to reopen if you have further questions
