### ISSUE TITLE
Detect async callback in Received.InOrder

### ISSUE THREAD

**Issue by tomasz-podolak** [nsubstitute/NSubstitute.Analyzers#133]

**Comment by tpodolak** [comment]
@dtchepak can you remove this one [please](https://help.github.com/en/github/managing-your-work-on-github/deleting-an-issue) ? I've accidentaly created this issue/task logged from my work account

**Comment by dtchepak** [comment]
> ... can you remove this one? I've accidentally created this issue/task using my work account

Sure. I've just enabled deletion for admins (so you are able to delete issues too if required).

I am deleting this issue now.
