### ISSUE TITLE
Quick-action for introducing fake in constructor argument

### ISSUE THREAD

**Issue by ffMathy** [nsubstitute/NSubstitute.Analyzers#138]
Let's say that I have `ServiceA` with dependencies `ServiceB` and `ServiceC`:

```csharp
class ServiceA {
    public ServiceA(ServiceB serviceB, ServiceC serviceC) { }
}
```

Now, if I type:

```csharp
var service = new ServiceA(
```

It would be awesome if Roslyn would suggest an action called `Introduce Substitute for ServiceB`, which would turn the code into:

```csharp
var fakeServiceB = Substitute.For<ServiceB>();
var service = new ServiceA(fakeServiceB
```

**Comment by tpodolak** [comment]
@ffMathy it seems to be possible to do that. Here are some preliminary results
![introducesubstitute](https://user-images.githubusercontent.com/7378346/77002889-9838fa00-695c-11ea-931c-0de669fa3c0f.gif)

**Comment by ffMathy** [comment]
Woah that'll be insanely useful! Can't wait until it is up! ♥️

**Comment by ffMathy** [comment]
Is there an ETA on when it'll be published to NuGet?

**Comment by tpodolak** [comment]
> Is there an ETA on when it'll be published to NuGet?
I've just opened PR for this feature so I guess we should be able to release it withint 1 or 2 weeks

**Comment by ffMathy** [comment]
Great to hear, and perfect that you linked this issue.

Looking forward to it. Thanks again.

**Comment by tpodolak** [comment]
@ffMathy released in [1.0.13](https://www.nuget.org/packages/NSubstitute.Analyzers.CSharp/1.0.13)

**Comment by ffMathy** [comment]
Hmmm @dtchepak these don't work for me in Visual Studio 2019 (latest update). Can you get them working? I noticed you're using Rider in your example.

**Comment by tpodolak** [comment]
I have only access to VS Community and it works fine there
![VisualStudio](https://user-images.githubusercontent.com/7378346/79910858-b7c1b780-841f-11ea-8c2c-b4751ef76773.gif)
Please note that usually Visual Studio doesnt pick up new rules/refactoring directly after package update/install so the restart is required
