### ISSUE TITLE
NS2001 For Internal class with Protected Internal constructor

### ISSUE THREAD

**Issue by akalnay** [nsubstitute/NSubstitute.Analyzers#144]
I am getting a NS2001 "Could not find accessible constructor" warning for a class with the internal access modifier and with a parameterless constructor that has the protected internal access modifier.  I believe that warning to be a false positive as I'm successfully creating a partial sub which is working as expected even though the warning is present.  The warning goes away if I change the constructor to protected instead of protected internal but I'd rather keep it as protected internal as that is the correct accessibility level.  I have the [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=...)] attribute in the assembly I'm testing.  My tests are in a friend assembly.

**Comment by tpodolak** [comment]
Hi @akalnay, that looks like bug to me. Thanks for reporting, will be fixed in the next release

**Comment by akalnay** [comment]
You’re welcome @tpodolak, but also thank you for your fine work with NSubstitute.
