### ISSUE TITLE
"NS1001 Member LogError can not be intercepted. Only interface ..." lying?

### ISSUE THREAD

**Issue by Saborion** [nsubstitute/NSubstitute.Analyzers#156]
While searching for a problem related to verifying that a call was made to a ILogger<T>.LogError() method, I stumbled across https://github.com/nsubstitute/NSubstitute/issues/539, which led me to this NSubstitute.Analyzers package. I installed the package in a project that verifies a lot of ILogger<T>.LogError() calls and the analyzer says:
_Warning	NS1001	Member LogError can not be intercepted. Only interface members and virtual, overriding, and abstract members can be intercepted._

I find this strange since those kind of assertions work just fine in this particular project. Sample unit test method below. NSubstitute version 4.2.2 and NSubstitute.Analyzers.CSharp version 1.0.14.

```csharp
// Arrange
const int id = 13;
var provisionService = Substitute.For<IProvisionService>();
var logger = Substitute.For<ILogger<ProvisioningController>>();
var exception = new CustomException("Hum-di-dum");
provisionService.Provision(id).Returns(x => { throw exception; });
var provisioningController = CreateDefaultProvisioningController(provisionService, logger, id);
var expectedLogMessage = "Slimmed down";

// Act
await provisioningController.Provision(subsId);

// Assert
logger.Received(1).LogError(exception, expectedLogMessage);
```
Has something changed somewhere along the line making this work?

**Comment by dtchepak** [comment]
Hi @Saborion ,

This isn't lying! 😄 We can't intercept that method. However, this can sometimes work "by accident" if the underlying calls the static member makes are to substitutes with interceptable members. It is generally a bad idea to rely on this, as even if this seems to work implementation changes can break the code in future (see: [1](https://stackoverflow.com/questions/60684578/cannot-test-iloggert-received-with-nsubstitute), [2](https://stackoverflow.com/questions/46529349/nsubstitute-ilogger-net-core), [3](https://stackoverflow.com/questions/48641906/how-to-use-an-nsubstitute-to-mock-the-logger)). I admit I have sometimes used this "by accident" property for implementations I control that I know are fairly safe to use/misuse in this way, and in these cases the warning can be suppressed.

Hope this helps.

**Comment by Saborion** [comment]
Hi,

Thanks for the reply. I will replace those "currently working implementations" with a manual fake for the reasons you mentioned. Thanks for the explanation.

Will try the "Close with comment" button to see if it does what I think it does, given that I considered this issue closed.
