### ISSUE TITLE
Constructor with params array triggers NS2002 and NS2004 on `For` and `ForPartsOf`

### ISSUE THREAD

**Issue by lonix1** [nsubstitute/NSubstitute.Analyzers#162]
Both `For<>()` and `ForPartsOf<>()` choke when a type's constructor contains a `params` array.

````cs
public class Foo {
  public Foo(string s, params object[] args) { }
}

public class FooTests {
  [Fact]
  public void TestConstructor() {
    Substitute.For<Foo>("hello");                     // NS2002
    Substitute.For<Foo>("hello", 10, true);           // NS2002
    Substitute.ForPartsOf<Foo>("hello");              // NS2002
    Substitute.ForPartsOf<Foo>("hello", 10, true);    // NS2002

    Substitute.For<Foo>("hello", 10);                 // NS2004
    Substitute.ForPartsOf<Foo>("hello", 10);          // NS2004
  }
}
````

NS2002:
> The number of arguments passed to NSubstitute.Substitute.For<Foo> do not match the number of constructor arguments for Foo. Check the constructors for Foo and make sure you have passed the required number of arguments. [MyProject.Tests]csharp(NS2002)

NS2004:
> Arguments passed to NSubstitute.Substitute.ForPartsOf<Foo> do not match the constructor arguments for Foo. Check the constructors for Foo and make sure you have passed the required arguments and argument types. [MyProject.Tests]csharp(NS2004)

**Comment by lonix1** [comment]
Hey @tpodolak / @dtchepak thanks for fixing this!

I noticed that the last release was almost a year ago. Any plans to push this to nuget?

**Comment by tpodolak** [comment]
Yes, we will release new version as soon as #160 and #159 is fixed
