### ISSUE TITLE
Add .netstandard2.0 target to NSubstitute.Analyzers.CSharp

### ISSUE THREAD

**Issue by bdovaz** [nsubstitute/NSubstitute.Analyzers#197]
Unity only works with .NET Standard 2.0+ and doesn't get along with older packages that don't explicitly support .NET Standard 2.0.

@tpodolak Is it ok if I make a PR to change it?

https://github.com/nsubstitute/NSubstitute.Analyzers/blob/dev/src/NSubstitute.Analyzers.CSharp/NSubstitute.Analyzers.CSharp.csproj#L3

**Comment by tpodolak** [comment]
Judging by https://stackoverflow.com/a/68424149/11779643 this should not be breaking change, so go ahead. However, change it  everywhere where applicable - there are more projects targeting `netstadnard1.3`. You might also need to check if `VSIX` projects are fine with that change. VISX extensions are not published but they are sometimes useful for debugging analyzers inside running VisualStudio instance
