### ISSUE TITLE
Disable CallInfo analysis when Arg.AnyType used for argument matching

### ISSUE THREAD

**Issue by tpodolak** [nsubstitute/NSubstitute.Analyzers#212]
https://github.com/nsubstitute/NSubstitute/pull/715#issuecomment-1708934821
https://github.com/nsubstitute/NSubstitute/pull/715#issuecomment-1712043274

**Comment by tpodolak** [comment]
@dtchepak from perspective of analyzer project [new NSubstitute version](https://github.com/nsubstitute/NSubstitute/pull/715#issuecomment-1711606401) seems to be introduced breaking change in the NSubstitute API. I have tons of failing tests after upgrade e.g
```csharp
using System;
using NSubstitute;
using NSubstitute.ReceivedExtensions;

namespace MyNamespace
{
    public interface IFoo
    {
        int? this[int? x] { get; set; }
    }

    public class FooTests
    {
        public void Test()
        {
            var substitute = Substitute.For<IFoo>();
            substitute.DidNotReceiveWithAnyArgs()[1] = Arg.Compat.Do<int>(__ => {});
        }
    }
}
```
```
Test0.cs(17,67): error CS0121: The call is ambiguous between the following methods or properties: 'Arg.Compat.Do<T>(Action<T>)' and 'Arg.Compat.Do<T>(Action<object>)'
```
Interestingly the same piece of code compiles just fine with `dotnet build` so I need to figure out how to fix analyzers tests in order to make analyzers aware of `Arg.AnyType`

**Comment by dtchepak** [comment]
> Interestingly the same piece of code compiles just fine with dotnet build so I need to figure out how to fix analyzers tests in order to make analyzers aware of Arg.AnyType

As in it only fails with VS? 🤔 Confirmed `dotnet test` fine on Mac.
