### ISSUE TITLE
Unify resource files

### ISSUE THREAD

**Issue by tpodolak** [nsubstitute/NSubstitute.Analyzers#22]
Currently, each analyzer library (C# or VB version) has its own Resources.resx file which contains messages for every diagnostic. As it was noted by @dtchepak 
 in https://github.com/nsubstitute/NSubstitute.Analyzers/pull/14#issuecomment-398041579 in most of the cases, the messages are the same and they only differ in some particular scenarios. Having that in mind we should find a way to share messages across analyzer libraries and override some of them when needed. Thanks to that approach we will avoid message duplication which will make the code-base cleaner and easier to maintain

**Comment by dtchepak** [comment]
This is excellent 👍
