### ISSUE TITLE
NS2003 triggers a warning when InternalsVisibleTo using strong name

### ISSUE THREAD

**Issue by Sebbstar** [nsubstitute/NSubstitute.Analyzers#79]
Describe the bug
We have to strong name all our assemblies.
NS2003 does not recognize InternalsVisibleTo syntax with publickey.

To Reproduce
our AssembyInfo.cs contains following line:
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")]

Expected behaviour
A clear and concise description of what you expected to happen, compared to what actually happened.

Currently i receive following warning:
Warning	NS2003
Can not substitute for internal type. To substitute for internal type expose your type to DynamicProxyGenAssembly2 via [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]

I'd expect not to receive any warning when using strong key.

Environment:

NSubstitute.Analyzers.CSharp 1.0.6
Platform: Windows10 - .net 4.6.2
Additional context
public static bool InternalsVisibleToProxyGenerator(this ISymbol typeSymbol)
{
return typeSymbol.ContainingAssembly != null &&
typeSymbol.ContainingAssembly.GetAttributes()
.Any(att => att.AttributeClass.ToString() == MetadataNames.InternalsVisibleToAttributeFullTypeName &&
att.ConstructorArguments.Any(arg => arg.Value.ToString() == MetadataNames.CastleDynamicProxyGenAssembly2Name));
}

arg.Value.ToString().StartsWith(MetadataNames.CastleDynamicProxyGenAssembly2Name) would quickly fix this issue ;-)

**Comment by tpodolak** [comment]
@Sebbstar thanks for reporting, fix is on the way
