### ISSUE TITLE
Is VS2019 supported?

### ISSUE THREAD

**Issue by simonvane** [nsubstitute/NSubstitute.Analyzers#99]
I just wanted to check if VS2019 is supported. 

The documentation is slightly ambiguous here - https://github.com/nsubstitute/NSubstitute.Analyzers/blob/master/documentation/Compatibility.md

Does it mean that only VS2017 is supported (above version 15.7) or does it mean that anything above Visual Studio 2017 version 15.7 is supported?

Thanks.

**Comment by tpodolak** [comment]
I've briefly tested it on VS2019 16.0.2 and it seems to be working fine. The [VS compatibility table](https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2017)  says that the Roslyn package we use (version 2.8.2) should be working fine for 

>Visual Studio 2017 version 15.7 or higher

which for my understanding means also for VS2019. However, just to be 100% sure I've added  issue/question on visual studio docs https://github.com/MicrosoftDocs/visualstudio-docs/issues/3147 to get the official statement

**Comment by tpodolak** [comment]
@simonvane looks like VS2019 should be supported by default as stated in https://github.com/MicrosoftDocs/visualstudio-docs/issues/3147#issuecomment-486844408. I will make this more clear in the docs.

**Comment by tpodolak** [comment]
@simonvane I am closing this one as docs were updated. Feel free to reopen if you think that docs are not good enough after the fix
